openapi: 3.0.3
info:
  title: Accelerate API
  version: 1.0.0
  description: API documentation for the Accelerate project
components:
  securitySchemes:
    sanctumAuth:
      type: http
      scheme: bearer
      description: Laravel Sanctum API token authentication
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: integer
          example: 1
        client:
          $ref: '#/components/schemas/Client'
        invoice_number:
          type: string
          example: INV-2025-0001
        total_ht:
          type: number
          format: float
          example: 300.00
        issue_date:
          type: string
          format: date
          example: 2025-05-01
        due_date:
          type: string
          format: date
          example: 2025-05-15
        status:
          type: string
          enum: ["draft", "paid", "cancelled"]
          default: "draft"
          example: "draft"
        lines:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLine'
      required:
        - id
        - client
        - invoice_number
        - total_ht
        - issue_date
        - due_date
        - lines
    Client:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
        phone:
          type: string
          example: 1234567890
        address:
          type: string
          example: 123 Main St
      required:
        - id
        - name
        - email
    InvoiceLine:
      type: object
      properties:
        id:
          type: integer
          example: 1
        description:
          type: string
          example: Service A
        quantity:
          type: integer
          example: 2
        unit_price:
          type: number
          format: float
          example: 50.00
        total_amount:
          type: number
          format: float
          example: 100.00
      required:
        - id
        - description
        - quantity
        - unit_price
        - total_amount
    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      required:
        - message
paths:
  /api/v1/clients/{id}:
    put:
      summary: Update a client
      description: Updates an existing client. Only accessible to admin users.
      operationId: updateClient
      tags:
        - Clients
      security:
        - sanctumAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the client to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Jane Doe
                email:
                  type: string
                  format: email
                  example: jane@example.com
                phone:
                  type: string
                  example: 0987654321
                address:
                  type: string
                  example: 456 St Michel
              required:
                - name
                - email
      responses:
        '201':
          description: Client updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  client:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
                    example: Client mise à jour avec succès !
        '401':
          description: Unauthorized - User not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Unauthenticated
        '403':
          description: Forbidden - User not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Vous n'avez l'autorisation d'effectuer cette action
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: The given data was invalid.
                errors:
                  email: [The email field is required.]
    delete:
      summary: Delete a client
      description: Deletes an existing client. Only accessible to admin users.
      operationId: deleteClient
      tags:
        - Clients
      security:
        - sanctumAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the client to delete
      responses:
        '200':
          description: Client deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Client supprimé avec succès
        '401':
          description: Unauthorized - User not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Unauthenticated
        '403':
          description: Forbidden - User not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Vous n'avez l'autorisation d'effectuer cette action